Default: &defaults
  database: PlainProject.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: PlainProject_test.sqlite3
  <<: *defaults

Staging:
  database: PlainProject_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: PlainProject_production.sqlite3
  poolsize: 100
  <<: *defaults
